#version 450
#define M_PI 3.1415926535897932384626433832795

layout (local_size_x = 1, local_size_y = 1) in;

layout (binding = 0, rg32f) uniform image2D pingpong;

void main(){
	ivec2 x = ivec2(gl_GlobalInvocationID.xy);

	float perms[] = {1.0, -1.0};
	int index = int(x.x+x.y) % 2;
	float perm = perms[index];

	float h = imageLoad(pingpong, x).r;
	imageStore(pingpong, x, vec4(perm*(h/65536.0f), perm*(h/65536.0f), 0, 0));

}